<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title></title>

  <?php $this->load->view('includes/head'); ?>
  <style>
    .policy-section {
      background: #fff;
      box-shadow: 0px 3px 21px 0px rgba(89, 100, 255, 0.08);
      padding: 1rem;
      margin-top: 2rem;
      border-radius: 0.6rem;
      margin-bottom: 2rem;
    }

    .policy-title {
      text-align: left;
      font-size: 2rem;
      margin: 0;
      font-weight: 700;
      padding: 1rem 0;
    }

    .pera {
      font-size: 1.02rem;
      font-weight: 500;
      margin: 1rem 0;

    }

    .list {
      padding: 0.6rem;
      font-size: 1rem;
      font-weight: 500;
    }
    .heading2 {
      font-size: 1.6rem;
      font-weight: 600;
      margin: 0;
      padding: 1.4rem 0;
    }
  </style>
</head>

<body>
  <!-- ::Start Header -->
  <?php $this->load->view('includes/header'); ?>
  <!-- ::End Header -->

  <!-- :: Start -->
  <div class="container">
    <div class="policy-section">

      <h1 class="policy-title">Privacy Policy</h1>
      <div class="content-box">
        <p class="pera">A privacy policy is a legal document which states all the possible ways that a party gathers, uses and manages a
          client’s data and it protects the personal data of client. This privacy policy governs the manner in which
          INDITAB.COM uses the information from users (or User) of the <a href="https://www.inditab.com/">INDITAB.COM</a>
          website. This privacy policy is applicable for the Website and all products and services which are offered by
          INDITAB.COM. For us privacy for our valued customer is very important. </p>
          <p class="pera">We strongly believe that the personal
          information of our customers should not be shared with the third party without the prior consent or request from
          the customer. That is why We at INDITAB ESOLUTIONS PVT LTD make sure that strict privacy policy is followed.
          Privacy is the right of an individual and at INDITAB ESOLUTIONS PVT LTD the information of the customer such as
          contact no., email, addresses etc. is used only for service opted only and not for any other purpose. Your contact
          information is stored in our database and is only used to contact you for updating you regarding the services you
          (our clients) have opted for. We at INDITAB ESOLUTIONS PVT LTD condemn the unauthorised reach and misuse and/or
          discloser of the personal information of the customer and we have strict guidelines and high security features to
          prevent the same. Any changes in our ‘Privacy Policy’ will be posted here on the website.</p>
      </div>
      <div class="about_bot_content">
        <p class="pera">This privacy is applicable on this website(including its mobile and App platform) and its products and services
          which are offered by <a href="https://www.inditab.com/">INDITAB.COM </a></p>
      </div>
      <div class="content-box">
        <h4 class="heading2">1. GENERAL</h4>
        <ul >
          <li class="list">This is an electronic record under Information Technology Act, 2000 and all the rules are applicable. The
            amended provisions pertaining to electronic records in various statutes as amended by the Information Technology
            Act, 2000. This document does not require any physical or digital signature as it is generated by a computer
            system.</li>
          <li class="list">Under the provision of Rule 3 (1) of Information Technology Rules 2011, this document is published. It
            required the publishing of rules and regulations, privacy policy and terms of usage of INDITAB.COM</li>
          <li class="list">The domain name INDITAB.COM (“Website”), is owned and operated by INDITAB ESOLUTIONS PVT LTD and having its
            registered office at #5, Site-IV Vikaspuri, Delhi-110018.</li>
          <li class="list">For the purpose of this Privacy Policy (“Policy”), wherever the context so requires,</li>
          <ul>
            <li class="list"> Here terms like ‘You’ &amp; ‘User’ are used for any person or entity accessing or using the services which
              are provided on this Website, who is competent to enter into binding contracts, as per the provisions of the
              Indian Contract Act, 1872;</li>
            <li class="list"> The terms ‘We’, ‘Us’&amp; ‘Our’ shall mean the Website and/or the Company as the context so requires.</li>
            <li class="list"> The terms ‘Party’ &amp; ‘Parties’ shall respectively be used to refer to the User and the Company
              individually and collectively, as the context so requires.</li>
          </ul>
          <li class="list"> The headings are given to each section in this Policy. This is done only for the purpose of organizing the
            various provisions under this Policy in an orderly manner. The party cannot use it to interpret the provisions
            contain herein in any manner. Further, it is specifically agreed by the Parties that the headings shall have no
            legal or contractual value.</li>
          <li class="list"> The user can use the Website which is governed under this Policy as well as the Terms of Use of the Website
            (“Terms”, available at www. INDITAB.COM), and any modifications or amendments made thereto by the Company from
            time to time, at its sole discretion. If the User visits the home page of the Website and/or using any of the
            services which are being provided on the Website shall be deemed to signify the User’s indisputable acceptance
            of this Policy and the previously mentioned Terms. The User understands and accepts that all Terms and Policy
            are interconnecting, and that expiry of any of one will lead to the termination of the other.</li>
          <li class="list"> The User indisputably agrees with all the Terms and Policy which legally bind the User and the Company, and
            that the User shall abide by the rules, guidelines, policies, terms, and conditions applicable to any of the
            services that are provided by the Website, and that the same is applied with the Terms, and shall be treated as
            part and parcel of the same. The User understands and accepts that no signature or express act is required to
            make these Terms and the Policy to bind the User. Under the User’s act, the User can visit any part of the
            Website with the acceptance of the Policy and the aforementioned Terms.</li>
          <li class="list"> It is agreed by all the parties that a Company/Website has all the rights to make a change in any of the
            policy and terms mentioned before without any prior notice to User/Users. The User accepts that any change or
            modification can be made immediately. It is User’s responsibility to keep him/her updated with all the Policy
            and Terms. If the User continues to use the Website following such a change, the User will be deemed to have
            consented to any and all amendments / modifications made to the Policy and Terms. In so far as the User complies
            with the Policy and Terms, he/she is granted a personal, non-exclusive, non-transferable, revocable, limited
            privilege to enter access and use the Website.</li>

        </ul>
      </div>
      <div class="content-box">
        <h4 class="heading2">2. COLLECTION OF PERSONAL AND OTHER INFORMATION</h4>
        <ul >
          <li class="list"> It is being accepted by the User that the contact information is collected and used by the company to provide
            services opted for, which is provided by the User from time to time on Website. The User’s need is fulfilled
            accordingly. This information is used by the Website/Company to improve the services for the User by providing
            regular updates.</li>
          <li class="list"> There is certain information which maybe tracked automatically by the Company/Website about the User like
            User’s IP address and User’s behavior on Website. The User knows that such information may include the URL that
            the User visited prior to accessing the Website, the URL which the User subsequently visits (whether or not
            these URLs form a part of the Website), the User’s computer &amp; web browser information, the User’s IP
            address, etc.</li>
          <li class="list"> If any User Chooses to buy any product or services from the Company/Website, the User is allowing the
            Company/Website to gather the personal information of the User.</li>
          <li class="list"> The User is aware that if any information which is provided by User whether it is posted message/ review /
            feedback anywhere on Website can be used by the Company/Website to help out the User in every possible way in
            future. This retained information can be used to resolve disputes, provide customer support, troubleshoot
            problems with such information, if requested, may be provided to judicial or governmental authorities of
            requisite jurisdiction, or otherwise used by the Company/Website as permitted by applicable laws.</li>
          <li class="list"> The Company/Website can ask or request the User to provide the reviews for the products/services which are
            purchased/ availed by the User from Website.</li>
          <li class="list"> The information like content/reviews/surveys/feedback which is submitted by the User to Company/Website may
            or may not be stored, uploaded, published or displayed in any manner. The User authorizes the Website/Company to
            remove any such content, review, survey or feedback from Website which has been submitted by User, without cause
            or being required to notify the User of the same.</li>
        </ul>
      </div>
      <div class="content-box">
        <h4 class="heading2">3. COOKIES </h4>
        <ul>
          <li class="list"> A cookie is an information which is being stored on hard disk by Website so that it can remember something
            about the User later time. The User is aware that this information that is Cookie is stored by the
            Website/Company to use it later if required and that cookies are useful for enabling the browser to remember
            information specific to a given user, including but not limited to a User’s login identification, password, etc.
            Web site installs permanent and temporary cookies in User’s hard disk and browser and the User is aware of it
            and does hereby expressly consent to the same.</li>
          <li class="list"> There are many data collection devices such as cookies on certain pages of the Website. These devices help in
            analyzing the web page flow, measure promotional effectiveness and promote trust and safety. These are the
            features which are only available due to the use of cookies. The User is aware of all this. While the User is
            free to decline the Website’s cookies if the User’s browser permits, the User may consequently be unable to use
            certain features on the Website</li>
          <li class="list"> Beside this, the User is aware that He/she might face other data collection devices like cookies on certain
            pages which are installed by third parties or affiliates on the Website. The User knows and accepts that the
            website/Company is not responsible as they do not control the use of such cookies/other devices by third parties
            and the User assumes any and all risks in this regard.</li>

        </ul>
      </div>
      <div class="content-box">
        <h4 class="heading2">4. SHARING OF PERSONAL INFORMATION </h4>
        <ul >
          <li class="list"> The Website/Company can share the personal information of User to detect and prevent identity theft, fraud,
            and other illegal acts. This information can be shared with corporate entities and affiliates to help them;
            correlate related or multiple accounts to prevent abuse of the Website’s services.</li>
          <li class="list"> The Website/Company has right to disclose the personal information of User if required to do so by law or if
            the Website/Company believes that such disclosure is reasonably necessary to respond to subpoenas, court orders,
            or other legal processes. This information can also be disclosed to law enforcement offices, third party rights
            owners, or other third parties if it believes that such disclosure is reasonably necessary to enforce the Terms
            or Policy; respond to claims that an advertisement, posting or another content violates the rights of a third
            party; or protect the rights, property or personal safety of its users, or the general public.</li>
          <li class="list"> If a Company/Website is merging with other Company/Website or in the event the of reorganization,
            amalgamation or reconstructing of the Company’s business, the Company/Website can share the personal information
            of User if required. Such business entity or new entity will continue to be bound be the Terms and Policy, as
            may be amended from time to time.</li>

        </ul>
      </div>
      <div class="content-box">
        <h4 class="heading2">5. SECURITY </h4>
        <p class="pera">
          All the transactions which are made on the Website are secure and protected. No information is disclosed while
          making the transaction on the Website as it is encrypted to protect the User against unintentional disclosure to
          third parties. Any information related to the User’s credit and debit card information is not received, stored by
          or retained by the Company / Website in any manner. This information is provided by the User directly to the
          payment gateway which is authorized to handle the information provided and is compliant with the regulations and
          requirements of various banks and institutions and payment franchisees that it is associated with.
        </p>
      </div>
      <div class="content-box">
        <h4 class="heading2">6. USER’S CONSENT</h4>
        <p class="pera">
          By using the Website and/ or by providing information to the Company through the Website, the User consents to the
          collection and use of the information disclosed by the User on the Website in accordance with this Policy,
          including but not limited to the User’s consent the Company/Website sharing/divulging the User’s information, as
          per the terms contained here in above in Section 4 of the Policy.
        </p>
      </div>
      <div class="content-box">
        <h4 class="heading2">7. DELIVERY POLICY </h4>
        <p class="pera">Delivery time of services opted by you vary with the service opted for. Some services are completely dependent on
          particular Government Authorities which cannot be by passed. INDITAB ESOLUTIONS PVT LTD and INDITAB.COM is not
          responsible for any delay on the part of the Concerned Authority.</p>
      </div>
      <div class="content-box">
        <h4 class="heading2">8. DISPUTE RESOLUTION AND JURISDICTION </h4>
        <p class="pera">Any dispute related to formation, interpretation and performance of this Policy will be solved through a two-step
          Alternate Dispute Resolution (“ADR”) mechanism. It is agreed by the Parties. It is further agreed to by the
          Parties that the contents of this Section shall survive even after the termination or expiry of the Policy and/or
          Terms.</p>
        <ul >
          <li class="list"> Mediation: If there would be any dispute between the parties, the Parties will attempt to resolve the dispute
            amongst themselves, with the mutual satisfaction of both Parties. If the Parties are unable to resolve the
            dispute between themselves within the period of thirty (30) days of one Party communicating the existence of a
            dispute to the other Party, the dispute will be resolved by arbitration, as detailed herein below;</li>
          <li class="list"> Arbitration: If the Parties are unable to resolve the dispute between them through Mediation, then it will be
            transferred forward to the Arbitration by a sole arbitrator to be appointed by the Company. The order passed by
            the sole arbitrator will be valid and binding on both Parties. The costs of proceedings will be borne by the
            Parties, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire
            cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be the
            city of Delhi, India.</li>

        </ul>
        <p class="pera">The Terms, Policy and any other agreements between the Parties are governed by the laws, rules and regulations of
          India and it is agreed by the Parties. The Courts at Delhi shall have exclusive jurisdiction over any disputes
          arising between the Parties.</p>
      </div>

    </div>
  </div>
  <!-- :: END -->



  <!-- :: START Footer  -->
  <?php $this->load->view('includes/footer'); ?>
  <!-- :: END Footer -->

  <?php $this->load->view('includes/foot'); ?>
</body>

</html>